/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    stacks: Stack;
    affiliates: Affiliate;
    leads: Lead;
    services: Service;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    stacks: StacksSelect<false> | StacksSelect<true>;
    affiliates: AffiliatesSelect<false> | AffiliatesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    about: About;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Assign one or more roles to this user.
   */
  roles: ('superadmin' | 'marketing' | 'sales' | 'user')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the image for accessibility and SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Articles, deep dives, and field notes from the ACE team.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stacks".
 */
export interface Stack {
  id: string;
  title: string;
  /**
   * URL-friendly identifier. Auto-generated from title if left blank.
   */
  slug: string;
  category: 'ai-strategy' | 'engineering' | 'case-studies' | 'field-notes';
  featuredImage?: (string | null) | Media;
  /**
   * Short summary shown on blog cards (max 280 chars).
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Affiliate partner links with click tracking.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliates".
 */
export interface Affiliate {
  id: string;
  partnerName: string;
  /**
   * The destination URL the user will be redirected to.
   */
  targetUrl: string;
  /**
   * Used in /go/[slug] redirect URL.
   */
  slug: string;
  /**
   * Toggle off to disable this affiliate link site-wide.
   */
  active: boolean;
  categoryTag?: ('cloud' | 'ai-tools' | 'software' | 'infrastructure' | 'analytics') | null;
  /**
   * Internal notes — why we partner with them. Not shown publicly.
   */
  description?: string | null;
  /**
   * Auto-incremented on each redirect.
   */
  clickCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Captured leads from website forms and lead magnets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  name: string;
  email: string;
  /**
   * Optional — company or organization name.
   */
  company?: string | null;
  /**
   * What challenges or goals the lead described.
   */
  painPoints?: string | null;
  source: 'contact-form' | 'lead-magnet-audit' | 'cta-footer';
  status: 'new' | 'contacted' | 'qualified' | 'proposal-sent' | 'closed-won' | 'closed-lost';
  /**
   * Private notes about this lead (not shown to the lead).
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  slug: string;
  shortDescription: string;
  order?: number | null;
  icon?: ('globe' | 'smartphone' | 'cpu' | 'trending-up' | 'code' | 'settings' | 'rocket' | 'layers') | null;
  colorTheme?: ('blue' | 'purple') | null;
  page?: {
    heroHeading?: string | null;
    heroDescription?: string | null;
    ctaButtonText?: string | null;
    features?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    whyUsHeading?: string | null;
    whyUsBody?: string | null;
    deliverables?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'stacks';
        value: string | Stack;
      } | null)
    | ({
        relationTo: 'affiliates';
        value: string | Affiliate;
      } | null)
    | ({
        relationTo: 'leads';
        value: string | Lead;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stacks_select".
 */
export interface StacksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliates_select".
 */
export interface AffiliatesSelect<T extends boolean = true> {
  partnerName?: T;
  targetUrl?: T;
  slug?: T;
  active?: T;
  categoryTag?: T;
  description?: T;
  clickCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  painPoints?: T;
  source?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  order?: T;
  icon?: T;
  colorTheme?: T;
  page?:
    | T
    | {
        heroHeading?: T;
        heroDescription?: T;
        ctaButtonText?: T;
        features?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        whyUsHeading?: T;
        whyUsBody?: T;
        deliverables?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Drag to reorder, add, or remove homepage sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  /**
   * Add, remove, and drag sections to reorder the homepage layout.
   */
  sections?:
    | (
        | {
            badgeText?: string | null;
            headlinePart1?: string | null;
            headlineHighlight?: string | null;
            headlinePart2?: string | null;
            narrative?: string | null;
            ctaButtonText?: string | null;
            secondaryButtonText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            textBefore1?: string | null;
            highlight1?: string | null;
            textMiddle?: string | null;
            highlight2?: string | null;
            textAfter?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'transition';
          }
        | {
            label?: string | null;
            headingPart1?: string | null;
            headingHighlight?: string | null;
            body?: string | null;
            ctaButtonText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'philosophy';
          }
        | {
            label?: string | null;
            heading?: string | null;
            description?: string | null;
            capabilities?:
              | {
                  title: string;
                  description: string;
                  icon?: ('cpu' | 'layers' | 'git-branch' | 'shield' | 'zap' | 'code') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'engine';
          }
        | {
            label?: string | null;
            heading?: string | null;
            description?: string | null;
            pillars?:
              | {
                  title: string;
                  description: string;
                  icon?: ('lightbulb' | 'code' | 'rocket' | 'target') | null;
                  capabilities?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'squads';
          }
        | {
            label?: string | null;
            heading?: string | null;
            description?: string | null;
            steps?:
              | {
                  number: string;
                  title: string;
                  stepLabel: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'loop';
          }
        | {
            label?: string | null;
            heading?: string | null;
            description?: string | null;
            articles?:
              | {
                  category: string;
                  title: string;
                  excerpt: string;
                  readTime?: string | null;
                  date?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'insights';
          }
        | {
            label?: string | null;
            headingPart1?: string | null;
            headingHighlight?: string | null;
            description?: string | null;
            ctaButtonText?: string | null;
            email?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            badgeText?: string | null;
            headingPart1?: string | null;
            headingHighlight?: string | null;
            description?: string | null;
            formHeading?: string | null;
            formDescription?: string | null;
            submitButtonText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'leadMagnet';
          }
        | {
            label?: string | null;
            heading: string;
            headingHighlight?: string | null;
            body?: string | null;
            ctaButtonText?: string | null;
            /**
             * URL or #section-id
             */
            ctaButtonLink?: string | null;
            style?: ('default' | 'subtle' | 'centered') | null;
            image?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'custom';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: string;
  hero?: {
    label?: string | null;
    headingPart1?: string | null;
    headingHighlight?: string | null;
    intro?: string | null;
    ctaButtonText?: string | null;
    email?: string | null;
  };
  mission?: {
    heading?: string | null;
    headingHighlight?: string | null;
    body1?: string | null;
    body2?: string | null;
  };
  vision?: {
    heading?: string | null;
    headingHighlight?: string | null;
    headingAfter?: string | null;
    body1?: string | null;
    body2?: string | null;
  };
  values?:
    | {
        title: string;
        description: string;
        icon?: ('target' | 'cpu' | 'shield' | 'lightbulb' | 'users' | 'rocket' | 'zap' | 'code') | null;
        id?: string | null;
      }[]
    | null;
  contact?: {
    heading?: string | null;
    headingHighlight?: string | null;
    description?: string | null;
    email?: string | null;
    responseTime?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              badgeText?: T;
              headlinePart1?: T;
              headlineHighlight?: T;
              headlinePart2?: T;
              narrative?: T;
              ctaButtonText?: T;
              secondaryButtonText?: T;
              id?: T;
              blockName?: T;
            };
        transition?:
          | T
          | {
              textBefore1?: T;
              highlight1?: T;
              textMiddle?: T;
              highlight2?: T;
              textAfter?: T;
              id?: T;
              blockName?: T;
            };
        philosophy?:
          | T
          | {
              label?: T;
              headingPart1?: T;
              headingHighlight?: T;
              body?: T;
              ctaButtonText?: T;
              id?: T;
              blockName?: T;
            };
        engine?:
          | T
          | {
              label?: T;
              heading?: T;
              description?: T;
              capabilities?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        squads?:
          | T
          | {
              label?: T;
              heading?: T;
              description?: T;
              pillars?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    capabilities?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        loop?:
          | T
          | {
              label?: T;
              heading?: T;
              description?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    stepLabel?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        insights?:
          | T
          | {
              label?: T;
              heading?: T;
              description?: T;
              articles?:
                | T
                | {
                    category?: T;
                    title?: T;
                    excerpt?: T;
                    readTime?: T;
                    date?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              headingPart1?: T;
              headingHighlight?: T;
              description?: T;
              ctaButtonText?: T;
              email?: T;
              id?: T;
              blockName?: T;
            };
        leadMagnet?:
          | T
          | {
              badgeText?: T;
              headingPart1?: T;
              headingHighlight?: T;
              description?: T;
              formHeading?: T;
              formDescription?: T;
              submitButtonText?: T;
              id?: T;
              blockName?: T;
            };
        custom?:
          | T
          | {
              label?: T;
              heading?: T;
              headingHighlight?: T;
              body?: T;
              ctaButtonText?: T;
              ctaButtonLink?: T;
              style?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        label?: T;
        headingPart1?: T;
        headingHighlight?: T;
        intro?: T;
        ctaButtonText?: T;
        email?: T;
      };
  mission?:
    | T
    | {
        heading?: T;
        headingHighlight?: T;
        body1?: T;
        body2?: T;
      };
  vision?:
    | T
    | {
        heading?: T;
        headingHighlight?: T;
        headingAfter?: T;
        body1?: T;
        body2?: T;
      };
  values?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        heading?: T;
        headingHighlight?: T;
        description?: T;
        email?: T;
        responseTime?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}